#!/usr/bin/env node
/**
 * The package is the source of truth; docs/ is a static site with no build step,
 * so it needs literal copies of the runtime (for the iframe) and of the client
 * (so the demo can `import` it without a bundler).
 *
 *   node scripts/sync-site.mjs          write the copies
 *   node scripts/sync-site.mjs --check  fail if they are stale (used before publish)
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pkg = join(root, "packages", "eval-sandbox");
const docs = join(root, "docs");

const BANNER = {
  js: (from) =>
    `// GENERATED by scripts/sync-site.mjs from ${from} — edit that file, not this one.\n`,
  html: (from) =>
    `<!-- GENERATED by scripts/sync-site.mjs from ${from} — edit that file, not this one. -->\n`,
};

const COPIES = [
  {
    from: join(pkg, "src", "sandbox", "evaluator.js"),
    to: join(docs, "sandbox", "evaluator.js"),
    banner: BANNER.js,
  },
  {
    from: join(pkg, "src", "sandbox", "index.html"),
    to: join(docs, "sandbox", "index.html"),
    banner: BANNER.html,
  },
  {
    from: join(pkg, "src", "index.js"),
    to: join(docs, "vendor", "eval-sandbox.js"),
    banner: BANNER.js,
  },
];

const check = process.argv.includes("--check");
let stale = 0;

for (const { from, to, banner } of COPIES) {
  const source = await readFile(from, "utf8");
  const expected = banner(relative(root, from).replaceAll("\\", "/")) + source;

  let current = null;
  try {
    current = await readFile(to, "utf8");
  } catch {
    /* not written yet */
  }

  if (current === expected) continue;

  if (check) {
    console.error(`stale: ${relative(root, to)}`);
    stale += 1;
    continue;
  }

  await mkdir(dirname(to), { recursive: true });
  await writeFile(to, expected);
  console.log(`wrote  ${relative(root, to)}`);
}

if (check && stale > 0) {
  console.error(`\n${stale} file(s) out of date — run \`npm run sync\`.`);
  process.exit(1);
}

console.log(check ? "docs/ is in sync" : "done");
